# Generated by Django 5.0.7 on 2025-10-26 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='medical_license',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='specialty',
            field=models.CharField(blank=True, choices=[('CARDIOLOGY', 'Cardiología'), ('DERMATOLOGY', 'Dermatología'), ('PEDIATRICS', 'Pediatría'), ('NEUROLOGY', 'Neurología'), ('ORTHOPEDICS', 'Ortopedia'), ('GYNECOLOGY', 'Ginecología'), ('PSYCHIATRY', 'Psiquiatría'), ('GENERAL', 'Medicina General'), ('SURGERY', 'Cirugía'), ('EMERGENCY', 'Emergencias')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='work_schedule',
            field=models.JSONField(blank=True, help_text='Horario de trabajo en formato JSON', null=True),
        ),
    ]
