# Generated by Django 5.0.7 on 2025-10-23 19:54

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_type', models.CharField(choices=[('lab_result', 'Resultado de Laboratorio'), ('prescription', 'Prescripción'), ('diagnosis', 'Diagnóstico'), ('note', 'Nota Médica')], default='note', max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('completed', 'Completado'), ('reviewed', 'Revisado')], default='pending', max_length=15)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('attachments', models.TextField(blank=True, help_text='URLs de archivos adjuntos (JSON)', null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medical_records', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medical_records', to='patients.patient')),
            ],
            options={
                'verbose_name': 'Registro Médico',
                'verbose_name_plural': 'Registros Médicos',
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
