# Generated by Django 5.0.7 on 2025-10-26 18:49

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VitalSign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperature', models.DecimalField(blank=True, decimal_places=1, help_text='Temperatura corporal en grados Celsius', max_digits=4, null=True)),
                ('blood_pressure', models.CharField(blank=True, help_text='Presión arterial (formato: 120/80)', max_length=10, null=True)),
                ('heart_rate', models.IntegerField(blank=True, help_text='Frecuencia cardíaca en latidos por minuto', null=True)),
                ('respiratory_rate', models.IntegerField(blank=True, help_text='Frecuencia respiratoria por minuto', null=True)),
                ('oxygen_saturation', models.IntegerField(blank=True, help_text='Saturación de oxígeno en porcentaje', null=True)),
                ('recorded_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('notes', models.TextField(blank=True, help_text='Observaciones adicionales')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vital_signs', to='patients.patient')),
                ('recorded_by', models.ForeignKey(limit_choices_to={'role__in': ['NURSE', 'DOCTOR', 'STAFF']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_vital_signs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Signo Vital',
                'verbose_name_plural': 'Signos Vitales',
                'ordering': ['-recorded_at'],
            },
        ),
    ]
